#!/usr/bin/env python3
"""Publish only generated catalog artifacts, with an explicit branch lease."""
import os, pathlib, shutil, subprocess, tempfile
from publish import verify

ROOT=pathlib.Path(__file__).resolve().parents[1]
BRANCH='refs/heads/catalog'
MARKER='.raily-generated-catalog'

def git(*args,cwd=ROOT,env=None):
    return subprocess.check_output(['git',*args],cwd=cwd,env=env,text=True).strip()

def publish(folder):
    verify(folder/'catalog/v1')
    remote=git('remote','get-url','origin')
    if not remote.rstrip('/').removesuffix('.git').endswith('FBukovina/raily-timetables'):
        raise ValueError('Refusing unexpected publication repository')
    expected=git('ls-remote','--heads','origin',BRANCH).split()
    expected=expected[0] if expected else ''
    env=dict(os.environ)
    # Actions checkout authenticates using a scoped local extraheader. Transfer
    # it in process environment (never URLs, command text, or printed logs).
    headers=subprocess.run(['git','config','--get-regexp',r'^http\..*\.extraheader$'],cwd=ROOT,text=True,capture_output=True)
    values=[line.split(' ',1) for line in headers.stdout.splitlines() if ' ' in line]
    if values:
        env['GIT_CONFIG_COUNT']=str(len(values))
        for i,(key,value) in enumerate(values):env[f'GIT_CONFIG_KEY_{i}']=key;env[f'GIT_CONFIG_VALUE_{i}']=value
    with tempfile.TemporaryDirectory(prefix='raily-catalog-publish-') as temp:
        checkout=pathlib.Path(temp)
        git('init','-b','catalog',cwd=checkout,env=env)
        git('remote','add','origin',remote,cwd=checkout,env=env)
        if expected:
            git('fetch','--depth','1','origin',BRANCH,cwd=checkout,env=env)
            actual=git('rev-parse','FETCH_HEAD',cwd=checkout,env=env)
            if actual!=expected:raise ValueError('Data branch changed during preparation')
            if git('show',f'{expected}:{MARKER}',cwd=checkout,env=env)!='Generated by raily-timetables; never store source or hand edits here.':
                raise ValueError('Refusing to rewrite a branch without the generated-data marker')
        for source in folder.iterdir():
            target=checkout/source.name
            if source.is_dir():shutil.copytree(source,target)
            elif source.name!='.git':shutil.copy2(source,target)
        (checkout/MARKER).write_text('Generated by raily-timetables; never store source or hand edits here.\n')
        git('config','user.name','Raily Timetables',cwd=checkout,env=env)
        git('config','user.email','41898282+github-actions[bot]@users.noreply.github.com',cwd=checkout,env=env)
        git('add','catalog',MARKER,cwd=checkout,env=env)
        git('commit','-m','Publish validated national timetable catalog',cwd=checkout,env=env)
        git('push',f'--force-with-lease={BRANCH}:{expected}','origin',f'HEAD:{BRANCH}',cwd=checkout,env=env)
        print(f'Published catalog branch {git("rev-parse","HEAD",cwd=checkout,env=env)}')

if __name__=='__main__':publish(ROOT/'site')
